version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      # Oper variabel public ke Dockerfile saat build
      args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
    container_name: nextjs-portfolio
    restart: always
    ports:
      - "3000:3000"
    # Baca file .env saat runtime
    env_file:
      - .env
